### ISSUE TITLE
ArchLinux package

### ISSUE THREAD

**Issue by fanningert** [openambitproject/openambit#100]
Hi,
I create a ArchLinux AUR package for this project.
https://aur.archlinux.org/packages/openambit/

My question now is, under which licence run this project?
MIT, GNU, ...

Regards
Thomas

**Comment by paddy-hack** [comment]
Mostly GPLv3+.  There are `COPYING` files in `src/libambit/` and `src/openambit/`.  The code in `src/movescount/` used to live below `src/openambit/` but didn't get a copy of the license when it was moved.

The only part that is possibly not GPLv3+ is below `wireshark_dissector/` which has a `COPYING` file that contains a BSD-style license.

**Comment by fanningert** [comment]
Ok, in the meantime I set the standard licence of the package to BSD and it were good when you put a central licence file in the root with the different licence types of the sub objects of this project.

**Comment by paddy-hack** [comment]
Uhm, I guess I should have mentioned that the `wireshark_dissector/` is not build by default and really only a developer oriented Wireshark plugin.  It is not needed for the day-to-day use of the `openambit` GUI.  With that in mind, I think that GPLv3+ makes a better choice for the standard license.

**Comment by fanningert** [comment]
Ok, I will change it to the GPLv3+ license.

**Comment by fanningert** [comment]
Ok, changed the licence of AUR package to GPL3+.
