### ISSUE TITLE
Missing error handling when no arguments are added

### ISSUE THREAD

**Issue by fanningert** [openambitproject/openambit#101]
I get this error when I execute `openambit2gpx.py` when I don't add any argument.

Tested with python 2.7 and 3.

```
Traceback (most recent call last):
  File "/usr/share/openambit/openambit2gpx.py", line 16, in <module>
    fileIn=sys.argv[1]
IndexError: list index out of range
```

**Comment by paddy-hack** [comment]
I guess it could show the `usage` message and exit with an error status.  I'll whip up and commit a patch.
