### ISSUE TITLE
Failed to automatically sync log entries to movescount.

### ISSUE THREAD

**Issue by superdupersvard** [openambitproject/openambit#106]
I was not able to get openambit to automatically sync log entries to movescount.com when the watch was connected to openambit.

I found out that in MainWindow::deviceDetected() that settings.beginGroup() was called and then SyncStart() was called, that also called settings.beginGroup() before settings.endGroup() has been called for the first settings.beginGroup(). This resulted in that the settings were not correctly read and that no sync with movescount was done.

I have made a fix for this in my branch ( https://github.com/superdupersvard/openambit ).
Github is new to me, so I am unsure how to proceed to get this fix in to the master branch.

**Comment by benedetto** [comment]
The help pages are your friend ;-)

Consider [the help pages on proposing changes in general](https://help.github.com/articles/proposing-changes-to-a-project-with-pull-requests/) and especially the [page on creating pull requests](https://help.github.com/articles/creating-a-pull-request).

**Comment by paddy-hack** [comment]
Seeing that you opened #107 and that I just merged that, I guess this question can be closed
