### ISSUE TITLE
Join the project

### ISSUE THREAD

**Issue by guigoutz13** [openambitproject/openambit#109]
Hello, 
I'm a French student at the end of an engineering school in digital science, in particular in software development. I have had an Ambit 3 for Christmas and when I have know this projet (openambit), I wanted join it !

To beginning, I would understand how run the software for the Ambit2. I read currently the code of libambit to understand how get the information with the usb protocol of the ambit2. But what is this protocol ? Can you help me to understand how get the log of the watch on the computer ?

Thanks you

**Comment by paddy-hack** [comment]
You may want to have a look at #54.
What seems most needed is a recent USB packet capture of the Ambit3 syncing to Movescount via Moveslink2.

**Comment by landas** [comment]
Closing issue without any recent activity. Feel free to reopen if issue is still relevant.
