### ISSUE TITLE
OSX building challenges :)

### ISSUE THREAD

**Issue by gregglind** [openambitproject/openambit#111]
I will add logs and debugs over the next few days.

Tried so far:

```
./build.sh
```

:)

**Comment by gregglind** [comment]
(issues so far:

1.  procutil / cores
2.  udev doesn't exist on osx. http://apple.stackexchange.com/questions/46951/is-there-a-mac-equivalent-for-udev-folder-on-linux

**Comment by landas** [comment]
Closing issue without any recent activity. Feel free to reopen if issue is still relevant.

**Comment by myadzel** [comment]
Is it possible to rewrite source code so that there is no dependency on udev?
