### ISSUE TITLE
Failed to get orbital data, Synchronization failed, movescount.com replied with " "" "

### ISSUE THREAD

**Issue by CratesDeThebes** [openambitproject/openambit#112]
Hi there,

I am using openambit 0.3-1 on several debian jessie installations. It used to work like a charm but two weeks ago it began to fail uploading logs to movescount. I tried to troubleshoot and I waited a bit because problems could have been related to movescount issues.

Now I think it may be a problem with openambit, may be movescount changed something in the protocol in a recent update ...

Symptoms : 
- In the GUI, i get the messages "Failed to get orbital data, Synchronization failed".
- In the terminal, when I try to force the upload of individual logs, i get the following message : 
  
  `Failed to upload log, movescount.com replied with " "" "`

**Comment by landas** [comment]
Closing issue without any recent activity. Feel free to reopen if issue is still relevant.
