### ISSUE TITLE
Linux Mint 18.1

### ISSUE THREAD

**Issue by JukkaWallin** [openambitproject/openambit#116]
'T\xc3\xa4m\xc3\xa4 PPA does not support xenial' When will new version PPA?

**Comment by guglez** [comment]
I'm also interested.

**Comment by vascotenner** [comment]
I am also interested. I just compiled from source. First install dependencies:

```
sudo apt-get install cmake gcc g++ libqjson0 libqjson-dev qt4-dev-tools qt4-default zlibc zlib1g zlib1g-dev libudev1 libudev-dev libusb-1.0-0 libusb-1.0-0-dev 
```

Then build as explained in Readme.md

I was not able to install via the built script.

**Comment by vascotenner** [comment]
These PPA with binary files work on xenial based systems according to @centic9: https://launchpad.net/~dominik-stadler/+archive/ubuntu/dsta-xenial-ppa

**Comment by centic9** [comment]
There were lots of changes to the code recently which should hopefully make Ambit3 work as well.  uploaded a recent version to the PPA at https://launchpad.net/~dominik-stadler/+archive/ubuntu/dsta-bionic-ppa, so I think this issue can be closed for now. 

Please create new issues for anything still missing.
