### ISSUE TITLE
Ambit 2 ("Duck") not detected

### ISSUE THREAD

**Issue by tzahialt** [openambitproject/openambit#117]
I have OpenAmbit (version 0.3) installed in Xubuntu 16.04 (in an Oracle VirtualBox VM).
My Ambit2 ("Duck") is detected by the OS (Produc Id 019), but still OpenAmbit says "No device detected".

tzahi@tzahi-VirtualBox:/usr/bin$ **lsusb**
Bus 002 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
**Bus 001 Device 003: ID 1493:0019 Suunto Duck [Ambit2]**
Bus 001 Device 002: ID 80ee:0021 VirtualBox USB Tablet
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub

OpenAmbit was installed using the following procedure :

For Ubuntu users

*buntu users can install prebuilt packets from our PPA at launchpad.

$ sudo apt-add-repository ppa:openambit/ppa
$ sudo apt-get update
$ sudo apt-get install openambit

**Comment by jadahl** [comment]
As far as I can tell, "Duck" is supported. Did you verify you have permission to read/write the device?

**Comment by tzahialt** [comment]
Thanks for your response jadahl.
Yes, according to other threads here, "Duck" should be supported.
As for permissions, could you suggest how do I check them, given the device location in my original post ?
Thanks.

**Comment by jadahl** [comment]
You could try

 $ ls -l /dev/hiddraw*

**Comment by tzahialt** [comment]
Thanks Jonas,
I'll give it a try when I'm in front of my pc.

**Comment by tzahialt** [comment]
Hi,

So I've followed these instructions : http://doc.sccode.org/Guides/HID_permissions.html

And I'm seeing :
tzahi@tzahi-VirtualBox:~/Desktop$ **ls -l /dev/hidraw***
crw-rw-r-- 1 root plugdev 248, 0 ינו 24 19:47 /dev/hidraw0
crw-rw-r-- 1 root plugdev 248, 1 ינו 24 19:49 /dev/hidraw1

and this :
tzahi@tzahi-VirtualBox:~/Desktop$ groups tzahi
tzahi : tzahi adm cdrom sudo dip **plugdev** lpadmin sambashare wireshark

and this :
tzahi@tzahi-VirtualBox:~/Desktop$ lsusb
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
**Bus 002 Device 003: ID 1493:0019 Suunto Duck [Ambit2]**
Bus 002 Device 002: ID 80ee:0021 VirtualBox USB Tablet
Bus 002 Device 001: ID 1d6b:0001 Linux Foundation 1.1 root hub

I'm running openambit from user **tzahi**, and still seeing the same problem : openambit saying "no device detected".

Any ideas ?
Is there any log I can check ?

Thanks.

**Comment by landas** [comment]
@tzahialt tell me if this still is an issue for you.

**Comment by JordiPujol** [comment]
hi nice people over there.
till now my suunto ambit 2 R works fine but today i get this error message

$ Failed to upload log (err code: QNetworkReply::NetworkError(ProtocolInvalidOperationError) ), movescount.com replied with " "\"Invalid CompressedTrackPoints: Invalid Altitude: valid range is [-1000, 15000] m\"" "
Failed to upload log, movescount.com replied with " "" "
Failed to upload log, movescount.com replied with " "" "
Failed to upload log, movescount.com replied with " "" "
Failed to upload log, movescount.com replied with " "" "
Failed to upload log, movescount.com replied with " "" "
Failed to upload log, movescount.com replied with " "" "
Failed to upload log, movescount.com replied with " "" "
Failed to upload log (err code: QNetworkReply::NetworkError(InternalServerError) ), movescount.com replied with " "\"Object reference not set to an instance of an object.\"" "
Failed to upload log (err code: QNetworkReply::NetworkError(InternalServerError) ), movescount.com replied with " "\"Object reference not set to an instance of an object.\"" "

i do every things us usual
the battery is charging in the suunto but no data is flowing, at least that seams.
is there is what ever more i can do just drop a mail. thanks
