### ISSUE TITLE
Support for Spartan possible?

### ISSUE THREAD

**Issue by dajoe** [openambitproject/openambit#118]
Is there any knowledge on the spartan models? I am considering a purchase and might be able to contribute. However, if this is out of scope of this project or too difficult to implement, I might stick to the Ambit, while they are still available.

**Comment by manisandro** [comment]
So the current situation is that the original maintainers are pretty much inactive, and there doesn't seem to be someone around anymore in the project with reverse engineering experience (someone please correct me if I'm wrong!). On my part I'm looking at keeping the project alive, but I can't give you a good answer as far as spartan feasibility is concerned unfortunately.

**Comment by 2Belette** [comment]
+1
I am looking for any opensource way to sync without being forced to push / publish my data into the cloud and I am considering Spartan or Garmin new 5S but both company force to use their cloud/app to update/use enhance capabilities...
Would be great to get the Spartan supported..

**Comment by mbernasocchi** [comment]
re the spartan, all the reverse engineering work was mainly done by @svenstorp. I've no experience with that. I do have some good contacts at Suunto, I'll try to see if they would be cooperative regarding the protocol layout

**Comment by mindrunner** [comment]
+1 :)
Can help coding as well. Maybe also reversing the protocol. But lets wait if maybe suunto is willing to help! :)

**Comment by mbernasocchi** [comment]
unfortunately not yet
""""
Hi Marco. I’m Markus from product management. Randel forwarded your request to give support regarding the Spartan communication protocol for OpenAmbit project. I’m sorry to say that we don’t have to capacity to support this kind of activity as we have our hands full specifying and executing our own work. Not impossible that we some day will open the communication a bit for external developers, but we want to manage that well and if we do it also serve a bigger audience and that’s why we currently are not able to help with this.
"""

**Comment by simdol** [comment]
I also own Suunto's Spartan Ultra. What exactly is there need to be done for openambit to support Spartan series? It would be really amazing if I could ditch Windows VM just for this. Come on Suunto, you have support for Windows & OS X but not GNU/Linux? Looking forward for update! :)

- Subscribed.

**Comment by KrisBoulez** [comment]
Did someone ever start on comparing the Ambit and Spartan communication protocol ?
Had a quick look and saw already some ascii readable stuff flying by.

**Comment by mbernasocchi** [comment]
@KrisBoulez not really I guess.

**Comment by KrisBoulez** [comment]
It is on my Summer-TODO-list.
Will see what it brings

**Comment by Gerold-R** [comment]
Does anyone has a PCAP file from a sync with a Spartan for me? I would like to compare the protocol. Thanks in advance

**Comment by KrisBoulez** [comment]
I have some pcap's lying around. 
Will dig them up and post later this week

Kris

**Comment by centic9** [comment]
Issue #232 talks about the same thing and has some USB captures and some more information on this topic, so I am closing this one as duplicate.
