### ISSUE TITLE
Moveslink2 working with Wine 2.3 Staging

### ISSUE THREAD

**Issue by Gerold-R** [openambitproject/openambit#122]
Hi, 

just tested again if original MovesLink2 (1.4.4) is running with Wine and yes it does. I installed Wine 2.3 Staging branch on a fresh installed Linux Mint 18.1 and after that DotNet Framework 4 (dotNetFx40_Full_x86_x64.exe). The Moveslink2 installprogram does not work, but I copied the necessary files from an installation on a Windows 7 PC into a created folder on the Linux desktop and I could start the app already. Than I copied the file "Settings.xml' into the "..\Suunto\Moveslink2" folder created by Moveslink2 after the first start. Than I connected my Ambit2S, changed the permissions of the USB device to read/write and started MovesLink2 again. It did found the watch and synced without problems. I made a screenshot after the sync. Maybe this is helpfull for someone with a watch not supported by OpenAmbit yet. 

I am quite sure that SuuntoLink for the Spartan is running too this way.

![moveslink2 on linux](https://cloud.githubusercontent.com/assets/16975317/23987440/e51578fc-0a29-11e7-96d4-42ed28ae9cc7.png)

**Comment by marguslt** [comment]
>  /../ The Moveslink2 installprogram does not work, but I copied the necessary files from an installation on a Windows 7 PC /../
You can actually find zipped Moveslink2 archives (+ few extras .. )  from Suunto's CouldFront and skip installation,  though I'm not sure now if settings.xml gets created by installer or application. I don't have a cable with me at the moment, but my guess is it's created after you entered details for Movescount and for that you first have to connect your watch.
https://www.google.com/#q=%22Moveslink2_1_4_3.zip%22

**Comment by Gerold-R** [comment]
Yes, I am aware of the files there. That's BTW how I found out which files are needed to run Moveslink2 without installation. There you can also find older Moveslink2 versions or currently the beta 1.4.5

The Settings.xml file is created after ML is closed but you can not sign in using ML this way cause ML needs Internet Explorer 9 (or higher?) for this. You can create an account (if not done already) using their website and add your email address and serialnumber manually into the xml file. To create a Userkey, you can use their Servicegate and add the key too.

**Comment by marguslt** [comment]
>  ML needs Internet Explorer 9 (or higher?) for this.

Oh yes, of course, good point.

**Comment by marguslt** [comment]
> but you can not sign in using ML this way cause ML needs Internet Explorer 9 (or higher?) for this

Oh yes, of course. Actually I'm bit surprised now that MC sign in / auth is only place where IE is needed. Anyway, nice find!
