### ISSUE TITLE
Sync navigation items (POIs / routes) (ambit2)

### ISSUE THREAD

**Issue by landas** [openambitproject/openambit#125]
I'm working on support for sync of the navigation items POIs (waypoint) and routes between device and movescount.

This is ongoing work, and at current stage it will **sync POIs only**, and **delete all routes** from device (due to protocol limits).

You can find my fork at: https://github.com/landas/openambit

It has a lot of added debug messages as it is ongoing work.

**Next stages:**
1) More investigation in the route protocol.
2) Fix better driver support. (driver API for navigation read/write WILL be changed)
3) Implement routes
4) Sync of personal settings 

**POIs sync:**
1) Download POIs (settings) from moves link 
2) Sync POIs added or deleted on device to movescount
3) Download POIs (settings) from moves link
4) Delete all waypoint/routes from device (only known protocol command)
5) Add downloaded (3) POIs from moveslink to device.

_The sync sequence is adopted from Windows movelinks2_

**Comment by benedetto** [comment]
Concerning your next stages point 4 (sync personal settings): maybe the work done by @superdupersvard in [his repo](https://github.com/superdupersvard/openambit) to sync sport modes could be helpful. Unfortunately his changes are not in the master, yet.

**Comment by landas** [comment]
Thanks for your comment @benedetto. Do you know the status of @superdupersvard sports mode code? Have you tested it? Does it work?

I have only taken a brief look at his code, but not tested it. Will do so after navigation is implemented.

I have just found out the last bits of the navigation protocol on the ambit, so I will soon start to implement code for it. :smile:

**Comment by landas** [comment]
I have now finished stage 1 - 3.

Tomorrow I will test a semi-long route with my bike to check that my calculation-formula is not way off what is expected on the ambit. On short walking routes, everything looks good now.

How would you like this to change to be pulled into master @mbernasocchi ? It is a big additions of code.
https://github.com/openambitproject/openambit/compare/master...landas:master

**Comment by superdupersvard** [comment]
Hi @landas 
This is great. 

About the sports mode. Sync of sports mode and also apps works in my implementation. At least for the sports mode/settings I tried. Maybe there are some settings that I missed. I will be great if you also have time to test it.

**Comment by benedetto** [comment]
@landas 
I can confirm that @superdupersvard's code is running fine concerning everything I tried so far.
