### ISSUE TITLE
Fail to get orbital data

### ISSUE THREAD

**Issue by Alcuza3** [openambitproject/openambit#126]
Hi everybody:
I'm writing from Spain. I,d like to thank your efforts for free us from windows slavery. So, i've had a problem with refreshing orbital data. Will you have a solution for fixing this problem?
Thanks a lot,in deed.

**Comment by landas** [comment]
Hi,

What modell do you have, and do you use the newest firmware version?

**Comment by Alcuza3** [comment]
Hi:
My watch is a Suunto Ambit 2s Black edition, bought last year.
And yes, I did it with the latest versión, despite the terrible warning.
When the moment of update orbital data, the application failed.

Thanks a lot for your quickly report.

Cesar


El 27 mar. 2017 7:14 p. m., "Lars Andre Landås" <notifications@github.com>
escribió:

Hi,

What modell do you have, and do you use the newest firmware version?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/openambitproject/openambit/issues/126#issuecomment-289496533>,
or mute the thread

**Comment by landas** [comment]
Hmmm... I have the Suunto Colibri [Ambit2 S] version, and have no problem with the orbital data.

When you say "the application failed", did it crash or did you get an orbit sync error message?

Could you try the following two steps:

**1) Run lsusb in terminal**

While the ambit is connected to your computer, run the command `lsusb` in terminal
Mine will return `Bus 001 Device 015: ID 1493:001a Suunto Colibri [Ambit2 S]`

Report back your version line.

**2) Compile with debug from github**

I don't know if you are familiar with compiling from source, but this could help us some extra error messages. You will need a developing environment with GNU C compiler and GNU C++ compiler and som Qt-dev packages. If you are on Ubuntu like me, you can run the following command for needed packages:

```
$ sudo apt-get install build-essential qt5-qmake qt-sdk libudev-dev libqjson-dev git
```
_If you are on another distribution you should, be able to install similar packages with your package manager._

Then go to a path in your home directory where you want to clone the openambit project, and run the following command:
```
$ git clone https://github.com/openambitproject/openambit.git
```
Then go into the newly created folder:
```
$ cd openambit
```

Compile and run (https://github.com/openambitproject/openambit/blob/master/README.rst):
```
$ ./build.sh -DCMAKE_BUILD_TYPE=Debug
```
```
$ ./run.sh
```

Report back if there is any error messages.

**Comment by landas** [comment]
@Alcuza3, did you get orbital data to work?
Yesterday I had problems updating orbital data at home, but at work today it is working again. I dont know if this is a problem with openambit or movescount.

**Comment by Gerold-R** [comment]
@landas If you think it's a Movescount problem, then simply try do download the SGEE file directly using the http link. Can you download the file, than it's not Movescount. For @Alcuza3's problem it may help to know the firmware and hardware version. Maybe there exists a version with an unknown address to store the SGEE data.

**Comment by Alcuza3** [comment]
Hi!:
Thanks for your support. These days I am recovering from an eyes surgery.
I will try to test your solution in a few days.
Thanks a lot indeed.

Cesar

**Comment by Alcuza3** [comment]
Hi Lars again:
This message is only to thank your help. I didi what you told me, and it´s
works¡
Yesterday night I was be able to update the orbit data in my watch. This
early morning I tested it, and works perfectly.
Thank you so much for your help. If you travel to Almeria anytime, there
will be two beers waiting for you If you warn me.

Cesar.

2017-04-06 21:29 GMT+02:00 César Jesús <alcuza3@gmail.com>:

> Hi!:
> Thanks for your support. These days I am recovering from an eyes surgery.
> I will try to test your solution in a few days.
> Thanks a lot indeed.
>
> Cesar
>
>
