### ISSUE TITLE
New release - 0.4

### ISSUE THREAD

**Issue by landas** [openambitproject/openambit#134]
1) I have drafted a new release (only visible to project members), but I don't know all new bug fixes and improvements that is worth mentioning. Could someone fill in missing bullet points?

2) Is there any issues that should be closed before 0.4 release?

3) We have to remember to update version number here before release: https://github.com/openambitproject/openambit/blob/ed204af960ca3b1ccc6e1f12cc586ddb639d4376/src/openambit/CMakeLists.txt#L4

Copy of current draft:

## Improvements
- #63 - Added internationalization (de, fr, it, ja, nb, nl, pl, sv)
- Added support for pool swimming sample uploads to movescount
- #130 Added support for syncing sport modes with movescount
- #125 Added support for syncing navigations items (waypoints and routes) with movescount

## Bugs
- Lots of bug fixed?

**Comment by manisandro** [comment]
Scanning the commits since 0.3, other things worth mentioning I see:
- Support Qt5
- Split movescount support to separate library

As for the issues, many open issues will most probably never see any activity again. I'd suggest closing these with "Closing issue without any recent activity. Feel free to reopen if issue is still relevant".

**Comment by landas** [comment]
I have closed a lot of old issues, with the text "Closing issue without any recent activity. Feel free to reopen if issue is still relevant".

I have added version numbers to CMakeLists.txt in commit 59f2a3ea98fd4a448f372bc4b31626bcd9d8d3a0

I think 0.4 is good to go, so who is resposible for releases? :smile:

**Comment by manisandro** [comment]
Good question, I suspect it's either you or me ;)

Would be nice to discover how to update the homepage, AFAICS it is not controlled through gh-pages.
Also, there is a PPA at https://launchpad.net/~openambit, I've sent a message to the owner to enquire about the PPA status resp. for having access so that we can update the packages there.

**Comment by landas** [comment]
The domain is owned by @svenstorp, and seems like it is hosted on a server owned by him.

Do you  know how the Debian package is updated? https://packages.debian.org/jessie/openambit

To release, is all we need to to click the "Publish release". Will the downloads be created automatically, or do we have to create them manually?

**Comment by manisandro** [comment]
Updating the Debian package is up to its maintainer (Christian Perrier <bubulle@debian.org>).
When you publish the release, links to tarballs for the release tag (i.e. a git archive for the tag) will appear on the download page. Any other downloads will need to be created manually, but I don't think any other are needed.
On my part I am maintainer for the Fedora package and I'll look at updating that one.

**Comment by manisandro** [comment]
Some code of a recent PR isn't QT5 compatible. Patch following soonish, perhaps worth holding off the release for a second?

**Comment by manisandro** [comment]
I've force-unpushed the 0.4 tag and pushed some fixes. As far as I can see things should be okay now.

**Comment by landas** [comment]
Thnx

**Comment by manisandro** [comment]
Perhaps do a quick check whether your recent works also works with Qt5, then I think we can do the 0.4 release.

**Comment by landas** [comment]
Could you tell me where i need to change config or flag to compile with Qt5 :smile:

**Comment by landas** [comment]
I found a way to compile with Qt5, but I had to add `option(USE_QT5 "Build against Qt5" ON)` to `src/movescount/CMakeLists.txt` and `src/openambit/CMakeLists.txt`.

The only way I can build this project is using `./build.sh`

When i try:
```
cmake .
make
```
the compiler complains about a lot of "undefined reference to ..."

I will test my code tomorrow if it works fine with Qt5.

**Comment by bubulle** [comment]
Quoting Lars Andre Landås (notifications@github.com):
> The domain is owned by @svenstorp, and seems like it is hosted on a server owned by him.
> 
> Do you  know how the Debian package is updated? https://packages.debian.org/jessie/openambit

*I* am in charge of this, as member of the Debian "pkg-running" group,
that maintains sport-related packages. I'm particularly concerned by
Openambit as a Suunto watch owner...and a frequent runner..:-)

However, the version in jessie and stretch *cannot* change: this is
Debian policy to never update software to upstream new version in
stable releases. jessie is the current Debian stable and stretch is
the next one, which is currently under freeze for an up-to-come
release.

So, I will update the Debian package, but I can do that only for the
Debian unstable release, that is the next Debian version, which is due
out....probably in 2 years.

So.....there if of course a solution with what we call "backports". 

There are specific Debian repositories named "jessie-backports" (and
"stretch-backports"....but only when Debian "stretch" is released) and
where updated packages can be uploaded with new upstream versions for
stable releases. Such packages are meant to be maintained as close as
possible to the Debian "stable" release, though security updates are
*not* guaranteed.

I will let you known, guys, about all this when I prepare Debian
packages for the 0.4 release.

For all this to happen....I just need an official release tarball
and....time..:-) (nowadays, I do much much much more running and
ultra-trail running than Debian packaging....:-) )

**Comment by landas** [comment]
@bubulle Thanks for your information about the Debian package. The snow is back in Norway, hopefully gone tomorrow again. Happy running. :smile:

@manisandro I have tested waypoints and routes with Qt5 to be ok.

**Comment by manisandro** [comment]
@landas Ok I'll tag the release then!

**Comment by centic9** [comment]
BTW, I have published version 0.4 plus current additional commits at the following Ubuntu PPAs:
* https://launchpad.net/~dominik-stadler/+archive/ubuntu/dsta-xenial-ppa
* https://launchpad.net/~dominik-stadler/+archive/ubuntu/dsta-yakkety-ppa
* https://launchpad.net/~dominik-stadler/+archive/ubuntu/dsta-zesty-ppa

(still built against QT4, the README needs an update for the new dependencies when QT5 is used)

**Comment by bubulle** [comment]
Quoting Lars Andre Landås (notifications@github.com):
> 1) I have drafted a new release (only visible to project members), but I don't know all new bug fixes and improvements that is worth mentioning. Could someone fill in missing bullet points?
> 
> 2) Is there any issues that should be closed before 0.4 release?


Hello fellow developers,

What's the status of the 0.4 release? I just went to the home page on
openambit.org but found nothing about 0.4. I guess there is still work
in progress, is there?

**Comment by landas** [comment]
Hi @bubulle,

As you know, we are a small team so you might have difficulty to find a package for your distribution. So you might have to compile it your self. The files for 0.4 release you find here:
https://github.com/openambitproject/openambit/releases/tag/0.4

Ubuntu: @centic9 has kindly created packages in his private PPAs. See post above.
Fedora: It is included in Fedora 26 Alpha

**Comment by bubulle** [comment]
Quoting Lars Andre Landås (notifications@github.com):
> Hi @bubulle,
> 
> As you know, we are a small team so you might have difficulty to find a package for your distribution. So you might have to compile it your self. The files for 0.4 release you find here:
> https://github.com/openambitproject/openambit/releases/tag/0.4


Hello Lars,

Well, my motiviation is precisely to create packages if you read
former contributions, as I'm the Debian maintainer of OpenAmbit.

However, for this, I mostly need an "official" tarball, which I could
use as a basis for this.

So, my point was mostly getting news on such last step of an official
release. Last time I read mails from the BTS, my understanding is that
there was some work about the release notes.....which seems to
indicate that you're near to complete the release. Am I wrong?

**Comment by manisandro** [comment]
Hi @bubulle 
Version 0.4 is released, the official tarball is the one which can be downloaded from the 0.4 release page (https://github.com/openambitproject/openambit/archive/0.4.tar.gz).

**Comment by landas** [comment]
@manisandro could these links be an answer to https://github.com/openambitproject/openambit/issues/134#issuecomment-296802989?
https://answers.launchpad.net/launchpad/+faq/21
https://answers.launchpad.net/~jonobacon

**Comment by manisandro** [comment]
@landas Worth a shot -> https://answers.launchpad.net/launchpad/+question/631021
