### ISSUE TITLE
Wrong charset encoding with Qt5 build

### ISSUE THREAD

**Issue by landas** [openambitproject/openambit#139]
When syncing ambit2 with a Qt5 build, it has wrong charset encoding.

Could it be json in Qt5 handling charset different than Qt4?

**Comment by manisandro** [comment]
Hmm, QJsonDocument (Qt5) assumes UTF-8 [1], not sure about QJson.
Where do the charset encoding issues appear? Can you compare the input json and the parsed QVariant to isolate?

[1] http://doc.qt.io/qt-5/qjsondocument.html#QJsonDocument

**Comment by landas** [comment]
The core of this issue is QString. Qt5 expects a UTF-8 string for the QString constructor [1].

This issue is still valid for sport modes (verified)
I don't know the status for log sync.

[1] https://wiki.qt.io/Strings_and_encodings_in_Qt

**Comment by landas** [comment]
> @manisandro ( issue #144 ): Mh so I suppose everywhere we are constructing a QString ambit data we should be using fromLatin1?

It looks like this is true. I think this is only a problem with the custom sports module now.

**Comment by landas** [comment]
I don't think there will be more trouble with this for now.
