### ISSUE TITLE
Qt5 - QNetworkReply::NetworkError(ProtocolInvalidOperationError)

### ISSUE THREAD

**Issue by landas** [openambitproject/openambit#144]
**This bug only show up when using non-english characters.**

With the Qt5 build, I get the following error when writing back settings to movescount.

"writePersonalSettingsInThread error: " QNetworkReply::NetworkError(ProtocolInvalidOperationError)

~~Seems like the PUT-request is not supported or supported different in QNetworkRequest (Qt5).~~

https://github.com/openambitproject/openambit/blob/8217647f68402adadb26adacf9c33e4e7476669d/src/movescount/movescount.cpp#L719

This bug results in waypoints (POIs) added in the ambit2 user interface, gets just deleted when syncing.

I can confirm this is not a problem with Qt4 build.

**Comment by landas** [comment]
This bug is related to #139.

When put-request do **not** contains non-english characters, the error does not show up.

**Comment by landas** [comment]
This could still be a problem for log uploads to movescount.

**Comment by manisandro** [comment]
Mh so I suppose everywhere we are constructing a QString ambit data we should be using fromLatin1?

**Comment by landas** [comment]
This issue (network error) does only affect the navigation module for now (fixed). Log upload do not send custom text strings.
