### ISSUE TITLE
Ambit3 Peak sync with 2.2.16 firmware

### ISSUE THREAD

**Issue by mpetazzoni** [openambitproject/openambit#149]
Hi all,

First of all, thanks for all the recent work on supporting the Ambit3 with openambit! It perfect timing because I'm having an issue getting an activity to sync to Movescount (the mobile app crashed while syncing it, and now it doesn't even try to sync it). So I'm trying to use openambit to get it back from the watch and push it to Movescount.

Unfortunately I'm having issues getting the sync to work. Built the latest `master` of this repository just fine, the app runs and sees the watch. It goes through the first motions but fails to read the logs:

```
Reading personal settings
Reading log files
Synchronization failed
```

In the console, all I get is:

```
Starting reading log...
libambit WARNING: get_memory_maps(): Failed to read memory map key
End reading log...
Outer space debug message
```

I understand the recent work on the Ambit3 is for the latest 2.4.1 firmware. Unfortunately I can't upgrade because that would wipe all data on the watch and I really don't want to loose this activity (Miwok100k ultra in 11:03, I really want that one up on Strava!).

I'm not sure where to go from there. What information can I get you to help debug? Should I try to get a capture with usbpcap? Any guidance on how to do that?

Thanks in advance!

**Comment by landas** [comment]
Hi,

To howto create usb dump with tcpdump:
https://github.com/openambitproject/openambit/issues/54#issuecomment-296797463

With wireshark:
http://openambit.org/wireshark-dissector/

**Comment by landas** [comment]
@mpetazzoni It might be a simple fix:

Try this branch: https://github.com/landas/openambit/tree/ambit3-fw2.2.16

When you clone it, remember to checkout ambit3-fw2.2.16

**Comment by mpetazzoni** [comment]
Thanks, I'll try that!

**Comment by mpetazzoni** [comment]
So, I had some time to give it a go tonight and sadly it doesn't work either. There's no error, and it ends with "Synchronization complete", but it doesn't actually list or sync any moves from the watch to the computer, even when checking "Resync all".

```
Start reading log...
Finished reading logs... I think...
Finished freeing data 1
Finished freeing data 2
End reading log...
Outer space debug message
```

What am I missing?

**Comment by landas** [comment]
I need some usb capture to see what is happening.

**Comment by mpetazzoni** [comment]
Ok, got the capture with tcpdump:

```
$ tcpdump -i usbmon2 -X > capture
```

Then ran the sync. Results are at http://code.bulix.org/sownoq-132855?raw

**Comment by landas** [comment]
@mpetazzoni, the log is not complete. Its stop in the middle of a data transfer.

**Comment by mpetazzoni** [comment]
Hmm, that's weird. I did another capture, and it looks like there's more stuff going on, but I can't tell if it has what you need: http://code.bulix.org/bpyqfn-138457?raw

Note that all my moves were already synced before. What I would like to know is if I can re-sync a previous move that wasn't actually transferred to Movescount correctly.

**Comment by mpetazzoni** [comment]
@landas Have you had a chance to look at the capture above? I really want to be able to sync that activity from my watch :)

**Comment by landas** [comment]
@mpetazzoni It was better, but it doen't help me. :(
Is it possible to get a log from windows moveslink, preferably with at least one move synced.

**Comment by mpetazzoni** [comment]
I don't have a Windows machine. I can try to get a capture where it actually has something to sync though. I'm still not sure I understand how openambit works though. Is it supposed to show me a list of the moves on the watch, with the ability to download/sync a specific one?

**Comment by wbarnard** [comment]
Support for Ambit 3 fw v2.2.16 (plus Ambit 3 Vertical and Suunto Traverse) is now available in my branch https://github.com/wbarnard/openambit/tree/extramodels.

This is ready for testing, if no problems I will create a pull request.

**Comment by mpetazzoni** [comment]
It does appear to work. At least, it seems to be making progress downloading the activities from the watch. Sadly, the activity I was most interested in has been aged out by the watch already and has been removed :(

**Comment by Gerold-R** [comment]
@mpetazzoni 
Maybe the developpers could add a new function to OpenAmbit: saving the complete memory where the exercise logs are stored to file. And instead of reading a log from the watch, a log could be read from the file and send to movescount. This would avoid to loose some activities in case of problems. Just an idea. I dont use OpenAmbit.

Also: it is possible to delete the Sync-Flag of an activity so that a new sync can be forced in case of problems like you had with your mobile app. Maybe another idea for OpenAmbit.

**Comment by mpetazzoni** [comment]
Yup, deleting the sync-flag to force a resync via the mobile app would be great. As I said unfortunately for my activity, it's too late now :( Thanks for the amazing work though!

**Comment by Gerold-R** [comment]
@mpetazzoni 
BTW: Did you try the app (from Android Playstore) called "Ambit Connect for Ambit3 Beta" from Green Peak Digital to recover the lost activity? This app gives you a better control than the original Movescount App from Suunto over the logs on the watch. At least that is what I heard from other users.

**Comment by gomesferreira** [comment]
WOW!!! @mpetazzoni  This is good... Where were you been all this time?? :-)

**Comment by mpetazzoni** [comment]
@Gerold-R I didn't know about it. As I said, sadly, the particular activity I really wanted to get out is gone now and has been aged out of the watch :(

@gomesferreira You mean as a forcing function for motivating someone to work on this?

**Comment by centic9** [comment]
Some support for Ambit3 was put in place in the meantime, I think we can close this general issue for now. 

Please report new issues for anything that is still not working.
