### ISSUE TITLE
GPS points not synced properly

### ISSUE THREAD

**Issue by makruiten** [openambitproject/openambit#150]
I'm on Fedora 26, running Openambit 0.4. The last two syncs, the map on Movescount is incomplete. Specifically, the starting point is shown incorrectly. All statistics, such as total distance, are correct, but the map isn't. In the provided screenshot, it should have been a full circle. The first 0.9 km is missing.

[log_E6C409510C001700_2017_05_14_12_49_56.log.txt](https://github.com/openambitproject/openambit/files/999360/log_E6C409510C001700_2017_05_14_12_49_56.log.txt)

![route](https://cloud.githubusercontent.com/assets/6661233/26033881/1f028f06-38b4-11e7-9845-be05da4e51a6.png)

This one skipped the first 3.4 km:

[log_E6C409510C001700_2017_05_11_11_16_00.log.txt](https://github.com/openambitproject/openambit/files/999394/log_E6C409510C001700_2017_05_11_11_16_00.log.txt)

![route-2](https://cloud.githubusercontent.com/assets/6661233/26034385/2c6acade-38bc-11e7-837a-f638392356e2.png)

[openambit.conf.txt](https://github.com/openambitproject/openambit/files/999398/openambit.conf.txt)

**Comment by benedetto** [comment]
I'm quite sure this is not an openambit issue. I also have such behaviour very now and then, where the GPS trace of beginning of a route is missing and I had those syncing both with openambit and the moveslink Windows client. TO me, it happens especially in cases where the watch hasn't been synced for a greater while -- something like more than 1.5 weeks or so.

I'm quite sure that the watch is only recording GPS points if the precision is below a certain threshold. If the watch hasn't been synced for some time, the satellite orbit data is too old to be precise and it has to collect these data from the GPS satellite signal. It can take some time until it has collected enough data to get a position with a reasonable precision. However, it still records all other values, it just can't put a geolocation on them.

You can see that on movescount by sliding with your mouse over e.g. the heart rate curve and watching the corresponding marker dot on the map. It should stay on the starting point for the first portion of the curve as long as the watch was not able to get a decent GPS reading.

**Comment by paddy-hack** [comment]
I have similar experiences when not syncing the orbital data for longer periods of time with the Ambit (i.e. the Ambit1).  However, in my case it does record the whole GPS trace but the points in the beginning are "all over the place".  This often leads to rather inaccurate distances (sometimes over 1km off when running) and sometimes to quite hilarious current speeds (running at 80  kph after a 400m 7% incline on a snowy sidewalk :grin: ) or world record split times (5km in 11:21, :1st_place_medal: ).

Also, I sometimes seem to experience interference of electricity wires running overhead.

**Comment by makruiten** [comment]
That sounds like this happening to me. I'm using a footpod, so the total distance and the pace were not too far off. 

Somehow, syncing orbital data didn't work for a while on my watch (with Openambit) and it would retry syncing indefinitely. Maybe that explains why it couldn't get the needed gps accuracy, because it certainly isn't my running frequency (I'm running about three times a week). This week it started syncing orbital data again, and indeed, the gps points are fine again. I'm closing this, as I agree with your observations.
