### ISSUE TITLE
Ambit3 Peak not supported?

### ISSUE THREAD

**Issue by gomesferreira** [openambitproject/openambit#158]
Hi,
I have installed Openambit 0.4 (qt5.7.1) on Fedora 26 Beta. It gives message that device it's still not supported.
Is there any other latest version supporting it?
Thanks!

![image](https://user-images.githubusercontent.com/29948471/27910030-3a444f28-624b-11e7-983a-a4ef41e9f2e9.png)

**Comment by krtek4** [comment]
Hi @gomesferreira ,

There's already an issue opened about this topic : https://github.com/openambitproject/openambit/issues/151

I'd suggest you close this one to keep the discussion in the same place.

**Comment by gomesferreira** [comment]
Thanks @krtek4. I agree. I just wanted to know if there is already an working SW for this.
