### ISSUE TITLE
Minor UI change - Main view - add splitter

### ISSUE THREAD

**Issue by tmattila** [openambitproject/openambit#161]
Hello,

I have hard times to see all data from selected log item. Space reserved for different parts are not given optimally and resizing form does not help. For this reason I added a splitter between sections so I can self tune the widths of different parts and now I can see all data that I need. Could this be part of release?

File: src/openambit/mainwindow.cpp
Method: contructor
```
MainWindow::MainWindow(QWidget *parent)
 {
    ui->setupUi(this);
    ui->actionE_xit->setShortcut(QKeySequence(QKeySequence::Quit));

    // Setup UI parts
    ...
    ui->syncProgressBar->setHidden(true);
<added code>
    QSplitter *splHorizontal = new QSplitter(ui->centralWidget);
    ui->horizontalLayout->addWidget(splHorizontal);
    splHorizontal->addWidget(ui->logsList);
    splHorizontal->addWidget(ui->logDetail);
    splHorizontal->addWidget(ui->deviceSyncWidget);
<added code end>
```
I added the code here (constructor), because I could not make it work via Qt Creator's form editor.

**Comment by manisandro** [comment]
Hi
Could you make a pull request with the change? Did you try as described in [1] to do it in the designer form?

[1] https://stackoverflow.com/questions/28309376/how-to-manage-qsplitter-in-qt-designer

**Comment by tmattila** [comment]
Hi
I did try (multiselection of controls + lay out xxx in splitter), but it did not behave as supposed - >  I added the code that I proposed.
I can do pull request later this week...

**Comment by tmattila** [comment]
My limited git bash experience is not making things easy. Would it be ok for you, @manisandro, to add those lines?

**Comment by manisandro** [comment]
You can also directly edit the file from your github fork page (i.e. fork openambit and then go to https://github.com/tmattila/openambit/edit/master/src/openambit/mainwindow.cpp) and then make a pull request, if you want the contribution to appear under your name. Or sure, I can do it.

**Comment by tmattila** [comment]
Thanks for info. At the moment I would be grateful if you could just do it. Main thing is that the change will be available.

**Comment by manisandro** [comment]
Done in d8ace78
