### ISSUE TITLE
Stuck at Reading Device Info

### ISSUE THREAD

**Issue by elShambler** [openambitproject/openambit#164]
I've read through a majority of the issues, especially those regarding the Ambit3 Peak. I'm pretty sure I ended up grabbing a copy from @landas branch - [link here](https://github.com/landas/openambit/tree/ambit3-fw2.2.16)

I'll try it with the most recent version of the master branch here, but it seemed like I went through all the right steps, but am still getting stuck here.

Is this potentially a cause of perhaps something I compiled incorrectly? I definitely tried going through all the issues here to troubleshoot. Maybe it's just the version of openambit I cloned?

Other useful information - I'm running Ubuntu 16.04 on a virtualbox with the Virtualbox Extension for reading the USB 2.0. I closed out Movescount on the Windows side. And I can run a tcpdump if necessary.

![openambit_inprocessofread](https://user-images.githubusercontent.com/1929353/29383003-8f81b5cc-829c-11e7-8a37-cc3cae4d6500.png)

**Comment by manisandro** [comment]
I'd try to run it inside `gdb` and print out a stack trace when the process is hung, this should give some more insight where things are stuck.

**Comment by landas** [comment]
Every issue I have looked into with this problem, the usb data stream stop unexpected from the ambit3. I don't know why.

**Comment by elShambler** [comment]
I attempted to use ```gdb``` using ```backtrace``` but when it gets to the same point of reading the device info, it hangs. Hitting CTRL+C at that point didn't stop ```gdb``` so I couldn't run ```backtrace```.

I then tried running the program in one shell, and ```gdb``` in another. The output was the same as what you see above along with the gdb output. I'll copy it down below. There is a chance I was using it incorrectly too as I was unfamiliar with doing a stack trace, so I followed some instructions I found at the Ubuntu wiki.

@landas - were you ever able to find a way to get the ambit to continue talking?

Output from ```gdb```:

> GNU gdb (Ubuntu 7.11.1-0ubuntu1~16.5) 7.11.1
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from openambit...done.
(gdb) handle SIG33 pass nostop noprint
Signal        Stop	Print	Pass to program	Description
SIG33         No	No	Yes		Real-time event 33
(gdb) set pagination 0
(gdb) run openambit
Starting program: /usr/local/bin/openambit openambit
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[Inferior 1 (process 2462) exited normally]
(gdb) Unable to create single instance. 
libambit INFO: ambit_device_info_new(): ignoring unknown device (VID/PID: 80ee/0021)
libambit INFO: ambit_device_info_new(): HID  : /dev/hidraw1: 'Suunto Ambit' (serial: A5AD0A5109001C00, VID/PID: 1493/001b)
Vendor: 1493, Product: 1b
libambit_komposti: 2 4 59 0
Komposit version: 2 4 59 0
libambit INFO: device_info_get(): Reading device info

**Comment by centic9** [comment]
I think there have been a number of changes to master in regards to support for Ambit 3 since this report, hopefully your issue is solved in the meantime, please try with the latest release and report back, if it still does not work for you.
