### ISSUE TITLE
Ambit3 Run, no device detected

### ISSUE THREAD

**Issue by Connando83** [openambitproject/openambit#166]
Hello,

I have to retrieve a move that has been canceled by mistake on the Movescount mobile app, and that seemingly I cannot sync again, although the file is still stored on the watch log. I suppose it is possible to do this and get a .gpx file or an equivalent with openambit, but I am new to it, and although I have set up the latest version through the following procedure:
``
$ sudo apt-add-repository ppa:openambit/ppa
$ sudo apt-get update
$ sudo apt-get install openambit ``

Openambit launches but still cannot detect my watch ("No device detected"). Linux seems to detect my watch however :
``
~ $ lsusb
Bus 002 Device 002: ID 0bda:0316 Realtek Semiconductor Corp. 
Bus 002 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 001 Device 006: ID 138a:0097 Validity Sensors, Inc. 
Bus 001 Device 005: ID 04ca:7066 Lite-On Technology Corp. 
Bus 001 Device 004: ID 8087:0a2b Intel Corp. 
Bus 001 Device 003: ID 1199:9079 Sierra Wireless, Inc. 
Bus 001 Device 002: ID 058f:9540 Alcor Micro Corp. AU9540 Smartcard Reader
Bus 001 Device 010: ID 1493:001e Suunto 
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
``

 Can somebody help me to sort this out ? I know this might seem a dumb request, but please note that I do not know anything of programming. My Linux Mint version is 18.1 Cinnamon 64 bits. Thanks for any help you can provide.

**Comment by gerhardol** [comment]
Latest Ambit3 does not seem to be supported. See #149 for a branch with support and for an Android app with support.

**Comment by centic9** [comment]
There was some more work in the meantime which should support Ambit 3, please reopen or create a new issue if you still have problems syncing.
