### ISSUE TITLE
Not possible to send "open water" activities to Movescount.com

### ISSUE THREAD

**Issue by runrun1234** [openambitproject/openambit#167]
It is not possible to send "open water" activities to Movescount.com with "master" branch (end of august) :
I get this :
`Failed to upload log (err code: QNetworkReply::NetworkError(ProtocolInvalidOperationError) ), movescount.com replied with " "\"Invalid CompressedTrackPoints: Invalid Altitude: valid range is [-1000, 15000] m\"" "`

I guess that because open water activities do not have altitude data (otherwise it would be crap : pressure sensor under 2 meters of water thinks that altitude is -1000 meters), then some wrong value is sent by openambit and movescount server does not accept it.

**Comment by centic9** [comment]
This will be fixed by #228 which adds checks on valid ranges for a number of fields

**Comment by runrun1234** [comment]
Thanks !
