### ISSUE TITLE
Porting of libambit to Android

### ISSUE THREAD

**Issue by starryalley** [openambitproject/openambit#179]
Hi, 

First of all it's not meant to be an issue.

I have to say Thanks to this excellent project. Two years ago when I first knew about it, I had an idea to port the project to Android so I could sync my watch while away from home without my PC. I quitted after 2 weeks of working due to other busy schedules. However I have found some time a week ago and had some outcome by now:

https://github.com/starryalley/AmbitSync

It's an app which has direct usage of libambit to read the watch. Hence I am here to share it. However I didn't plan to implement the Movescount upload part. I simply made a decision to export the log samples into GPX files directly on the phone, without using internet.

Sorry for opening this issue but I do hope that someone could finally finish what I have not yet done to get openambit on Android! For supporting Android, I would suggest the initial steps to go:

1. update to latest libusb where there is some initial support for Android. However something is still missing there. For example, it is prohibited to enumerate all USB devices on Android as a regular user.
2. for hidapi it is necessary to modify according to libusb's support for Android.
3. no big change is necessary on libambit, simply add a new function or two to support passing the file descriptor of the USB device from outside world, which is necessary for Android.

Thank you again for creating this awesome project. I'm a happy user of it. Hopefully this app I created is useful to some, if any.

**Comment by skinnie** [comment]
Thanks for your contribution. I will give it a try.I was looking for something like that...in fact I also trying this one, but could manage to compile it:
https://github.com/kekepins/alt-scount

Hope it helps so in the future we can have offline acess to most of the settings in our ambit watches

**Comment by skinnie** [comment]
Tried to install it on My 2012 Nexus 7 3G (running 4.4.4 ) and won't let me install the apk

**Comment by starryalley** [comment]
Yeah it's expected. I should have used earlier SDK/NDK version to build the apk. It's now targeted to Android 7.0/8.0 devices. I'll find some time to re-build it.

**Comment by centic9** [comment]
FYI, I just pushed an update to the latest hidapi-code from https://github.com/signal11/hidapi, this added some support for Android to the libusb hid-version, not sure if this improves anything for AmbitSync.

Anyway I think this issue is mostly "done", thanks for using libambit in this way and let us know if there is anything that we can include in the Openambit code which would reduce the overhead of maintaining it on your side.
