### ISSUE TITLE
Not an issue but I think it's good to know

### ISSUE THREAD

**Issue by Gerold-R** [openambitproject/openambit#182]
DevOps:
You can resurrect any deleted GitHub account name. And this is why we have trust issues.

Read more here:
https://www.theregister.co.uk/2018/02/10/github_account_name_reuse/

@Admin
If it's not considered important, sorry. Please delete.

**Comment by centic9** [comment]
It is good to know, but I am closing this here as it is not a problem in Openambit per se, but something that Github needs to solve.
