### ISSUE TITLE
tools/openambit2gpx.py and python v3.6.1

### ISSUE THREAD

**Issue by gabalawi** [openambitproject/openambit#183]
With python 3.6.1 I get an error "TypeError" in calls fOut.write(...etree.toString(trk)...) and fOut.write(... etree.toString(lap) ...), see below.
Putting "etree.toString(trk, encoding='unicode')", "etree.toString(lap, encoding='unicode')" solved this for me.

`[heinz@imru tools]$ ./openambit2gpx.py ~/.openambit/log_F88309511D000E00_2018_02_24_19_15_34.log ./test.gpx
Traceback (most recent call last):
  File "./openambit2gpx.py", line 147, in <module>
    fOut.write("   "+etree.tostring(trk)+"\n")
TypeError: must be str, not bytes`
[...]
`Traceback (most recent call last):
  File "./openambit2gpx.py", line 253, in <module>
    fOut.write("  "+etree.tostring(lap)+"\n")
TypeError: must be str, not bytes`

**Comment by benedetto** [comment]
I had the same problem and tried the same fix. Unfortunately this fix prevents running the script on python2...

**Comment by centic9** [comment]
Fixed now in a different way which still allows to run with Python 2.x via PR #209
