### ISSUE TITLE
v0.3 cannot sync with Movescount

### ISSUE THREAD

**Issue by Fruchtenstein** [openambitproject/openambit#184]
Openambit v0.3 (installed from Ubuntu 17.10 repositories) sometimes refuses to sync a new run with the following message:
"LocalTime values must be in ascending order (2018-05-01T13:53:06.036 is before 2018-05-01T13:20:41.539)"

Neither of the two timestamps can be found in the log file.

The log was downloaded from Ambit2 R: 
[log_E3C409511D001A00_2018_05_01_13_14_16-2.log.gz](https://github.com/openambitproject/openambit/files/1963724/log_E3C409511D001A00_2018_05_01_13_14_16-2.log.gz)

**Comment by mbernasocchi** [comment]
please check with 0.4
