### ISSUE TITLE
Orbital data

### ISSUE THREAD

**Issue by aeszter** [openambitproject/openambit#188]
Hello,
one question regarding orbital data: is it possible to export this to a file in order to use it with the gps_track_pod project?

Thanks,
A.

**Comment by alkino** [comment]
Hi,
If you know a bit of programming you can use libmovescount to get orbital data `getOrbitalData` and output it on a file.
Are you able to do it?

**Comment by aeszter** [comment]
Hi alkino,
thanks a lot for your hint. I'll look into it as soon as I have the time.

A.

**Comment by centic9** [comment]
Question was answered so I think we can close this issue for now.
