### ISSUE TITLE
Flatpak or Snap Package ?

### ISSUE THREAD

**Issue by btqy** [openambitproject/openambit#202]
Hello,
Due to library problems (Qjson and Udev), Openambit seems to be very difficult to compile in Solus distribution. Perhaps it is the case for others distrib when the binaries don't exist.
It will be great if you can propose Flappak or Snap Package, it will solve all the problems.
Do you think you can do it?
I really like Openambit but since I leaved Ubuntu/Mint to Solus, I'm very frustrated not to be able to get Openambit.
Many Thanks for your help

**Comment by centic9** [comment]
Sorry, but I actually try to avoid snap on Ubuntu and don't use Flatpak at all, so unless scripts for such packaging are contributed by someone else, this will likely not happen.
