### ISSUE TITLE
Qt components installation

### ISSUE THREAD

**Issue by mortenko** [openambitproject/openambit#203]
Hi Guys, 
I'm trying to install openambit for my suntoo ambit3 peak nepal edition on linux fedora workstation.

Actually Im installing qt using qt installer.There is a installation step "select components". Do I need all of them ? It takes over 7GB. 
![qt_components](https://user-images.githubusercontent.com/9746228/46162211-e7cac800-c287-11e8-92f1-44a4601492a4.png)

thanks for answer

**Comment by alkino** [comment]
Hi, I'm on Fedora too.

Simply `sudo dnf install qt5`.

**Comment by centic9** [comment]
I think the question was basically answered and there is not much that can be done here, so I am closing this for now.
