### ISSUE TITLE
Suunto 9 (baro)

### ISSUE THREAD

**Issue by lukasc-ubc** [openambitproject/openambit#224]
Is there a possibility of downloading from a Suunto 9 watch?  There are likely some differences between the Ambit 3 and Suunto 9 watches, as Suunto has different download software (Suuntolink for Suunto 9, versus Moveslink2 for Ambit watches).

thank you

**Comment by centic9** [comment]
If you are still interested, the usual approach is to get some USB logs captured, see https://github.com/openambitproject/openambit/issues/54#issuecomment-296797463 for how to do that, then someone with re-engineering experience can take a look and at least state if it is feasible to support it or not.

**Comment by centic9** [comment]
Closing this one for now, please reopen with some logs if there is still interest for getting this into Openambit. But chances are high that the protocol is fairly different so unless someone with access to that hardware wants to put some effort into it chances are slim to be able to support it.
