### ISSUE TITLE
OpenAmbit auto start

### ISSUE THREAD

**Issue by sylvainbx** [openambitproject/openambit#225]
OpenAmbit launches automatically at system startup. 
I'm using kde/plasma-5 so I was expecting this is due to a .desktop file in ~/.config/autostart but there's nothing there ... how to disable this behavior?

**Comment by paddy-hack** [comment]
Maybe a distribution dependent issue, if you're using a pre-packaged binary.  Please provide distribution info and what OpenAmbit version you are using (pre-packaged, compiled from source, etc).

That said, there's also `/etc/xdg/autostart/` and perhaps similar.  Look at the system-wide locations where this might be auto-started.

**Comment by sylvainbx** [comment]
Thanks for your reply.
Here's the info about my distribution and my openambit installation :
```
$ lsb_release -a
No LSB modules are available.
Distributor ID: neon
Description:    KDE neon LTS User Edition 5.12
Release:        18.04
Codename:       bionic
$ apt show openambit
Package: openambit
Version: 0.4-1ubuntu0~git20181118~ppa2
Priority: optional
Section: utils
Maintainer: Debian running development group <pkg-running-devel@lists.alioth.debian.org>
Installed-Size: 328 kB
Depends: libambit0, libc6 (>= 2.4), libgcc1 (>= 1:3.0), libqt5core5a (>= 5.9.0~beta), libqt5gui5 (>= 5.7.0), libqt5network5 (>= 5.0.2), libqt5widgets5 (>= 5.0.2), libstdc++6 (>= 4.1.1), libudev1 (>= 183)
Download-Size: 98,4 kB
APT-Manual-Installed: yes
APT-Sources: http://ppa.launchpad.net/dominik-stadler/ppa/ubuntu bionic/main amd64 Packages
Description: utilities for Suunto Ambit sport watches
```
Sadly, I found nothing about openambit in `/etc/xdg/autostart/` neither in other autostart folder.

**Comment by paddy-hack** [comment]
Hmm, KDE neon, an Ubuntu derivative, with Openambit from someone's PPA.  Suggest you ask there first.

That said, if OpenAmbit launches automatically at system start up, that might be "courtesy" of `systemd` (of which I am no fan).  If it only launches automatically when you connect your Ambit, it's probably something triggered by `udev` (appropriated by `systemd` nowadays).

AFAIK, there is nothing in the Openambit sources that facilitates launching anything automagically.

**Comment by centic9** [comment]
I'm providing that PPA, no change related to autostarting there, it just follows newer Git than the released versions.

**Comment by sylvainbx** [comment]
Well this is a mistery... `systemctl list-units` reports nothing related to openambit and it didn't lauches when I plug the watch but at desktop startup.
I thought it was an expected behavior but I'll investigate on this when I'll have free time and keep you updated.

**Comment by marguslt** [comment]
@sylvainbx , what's your login setting for desktop session?
https://userbase.kde.org/System_Settings/Startup_and_Shutdown#Session_Management

And do you actually exit from Openambit or you just close the window so it keeps running in background / system tray? It's probably just the last session that gets restored, but if there's something broken with sessions and you want to manually fix or clear those, config should be stored in  _~/.config/ksmserverrc_

**Comment by sylvainbx** [comment]
@marguslt I think you've found the point, thank you!
I didn't exited OpenAmbit correctly, I was just closing the window so the kde session restauration process was opening it again on each startup.
Thanks everyone for your help.
