### ISSUE TITLE
Error when using openambit2gpx.py script

### ISSUE THREAD

**Issue by YannChemin** [openambitproject/openambit#230]
python openambit2gpx.py log_xxxxxxx_2018_04_19_16_18_06.log log_xxxxxxx_2018_04_19_16_18_06.gpx
Traceback (most recent call last):
  File "openambit2gpx.py", line 266, in <module>
    fOut.write("  "+etree.tostring(lap)+"\n")
TypeError: can only concatenate str (not "bytes") to str

same at line 158 with "trk"

**Comment by hdoupe** [comment]
I ran into this problem, too.

**Comment by centic9** [comment]
This seems to be the same issue as #183, therefore closing this one here as duplicate.
