### ISSUE TITLE
ambit error

### ISSUE THREAD

**Issue by JordiPujol** [openambitproject/openambit#240]
when try to down load data from ambit 3 peak get this error
libambit_komposti: 2 4 59 0
Komposit version: 2 4 59 0
Start reading log...
Finished reading logs... I think...
Finished freeing data 1
Finished freeing data 2
End reading log...
Outer space debug message
Failed to upload log (err code: QNetworkReply::NetworkError(ProtocolInvalidOperationError) ), movescount.com replied with " "\"Invalid CompressedTrackPoints: Invalid Altitude: valid range is [-1000, 15000] m\"" "
Failed to upload log, movescount.com replied with " "" "
Failed to upload log, movescount.com replied with " "" "
Failed to upload log, movescount.com replied with " "" "
Failed to upload log, movescount.com replied with " "" "
Failed to upload log, movescount.com replied with " "" "
Failed to upload log, movescount.com replied with " "" "
Failed to upload log, movescount.com replied with " "" "
Failed to upload log (err code: QNetworkReply::NetworkError(InternalServerError) ), movescount.com replied with " "\"Object reference not set to an instance of an object.\"" "
Failed to upload log (err code: QNetworkReply::NetworkError(InternalServerError) ), movescount.com replied with " "\"Object reference not set to an instance of an object.\"" "
Failed to upload log (err code: QNetworkReply::NetworkError(ProtocolInvalidOperationError) ), movescount.com replied with " "\"Invalid CompressedSampleSets: Invalid Distance: valid range is [0, 99999000] m\"

any help will be welcome

**Comment by centic9** [comment]
This will probably be "fixed" by #228 by not sending those invalid values, although it is strange where these invalid values are coming from in the first place, sounds like a bug on the watch itself.

**Comment by gustavo-iniguez-goya** [comment]
Yeah @centic9 . As far as I can tell, the watches do not filter the values recorded, so when there're GPS connectivity errors or not enough satellites (in forests for example) you get wrong values inserted in the log.

In my experience, by not sending the wrong values mitigates this problem, but sometimes the GPS track is so badly recorded that it's unusable.

**Comment by centic9** [comment]
This should be fixed now after #228 is merged.
