### ISSUE TITLE
Differences between Moveslink2 and Openambit

### ISSUE THREAD

**Issue by bubuche79** [openambitproject/openambit#246]
Hello,

I have a Suunto Ambit3 Vertical. When I compare an "official" log from Suunto Moveslink2 and a log from Openambit, I have a few differences. I assume this is unexpected.

See attached [moveslink.zip](https://github.com/openambitproject/openambit/files/4269353/moveslink.zip) file (I have stripped some floating decimals to remove rounding issues).
- Some elements are missing (header, R-R)
- Probably more critical, some values are wrong (Cadence, Custom and a few other ones)

I have the latest code (218b8091de5551659fca9763e4b30ecf89b8e497).

Bubuche

**Comment by centic9** [comment]
Openambit stores what the Watch reports as original collected values. Moveslink/Movescount then performs some processing on the move, smoothing, calculating, adjusting or whatever. As the actual things done to the raw data are not documented, Openambit cannot do the same changes and thus only can provide you the "raw" values as provided by the watch.

You may also need to perform some adjustment of units if you compare values from the watch and from Movescount, e.g. some values from the watch are reported as multiplied by 10 or 1000 to keep the number as integer even for decimal values to avoid decimal arithmetic in the watch firmware, e.g. PTE, temperature, ....

Overall I don't think there is much Openambit can do, unless you spot a certain value that seems to be written incorrectly altogether, i.e. mixed up values or empty values where the watch actually reports some value...
