### ISSUE TITLE
No longer works on Ubuntu 19.10 and upcoming 20.04 (Qt4 deprecated)

### ISSUE THREAD

**Issue by ALchEmiXt** [openambitproject/openambit#249]
The openambit as a package has been removed from the ubuntu repository for versions 19.10 and up. Since they are actively deprecating all Qt4-based software and libraries.... Any plans for migrating to Qt5?

I was so happy that I could connect my watch but now it fails since 19.10 and will not work with the current code base in 20.04 either.

Currently the software hangs (at least) on missing library;
`openambit: error while loading shared libraries: libqjson.so.0: cannot open shared object file: No such file or directory`

Related to issue #202 

Keep up the good work! Appreciated!

**Comment by centic9** [comment]
We unfortunately do not have much influence on Debian/Ubuntu packaging right now, Qt5 support was available on latest master for some time, but the package still got removed, maybe an official release with this was missing (which is available now as 0.5).

If you would like to install it via deb-packages on Ubuntu or Debian, there are fairly up-to-date PPAs at the following locations:

* https://launchpad.net/~dominik-stadler/+archive/ubuntu/dsta-bionic-ppa
* https://launchpad.net/~dominik-stadler/+archive/ubuntu/dsta-eoan-ppa
* https://launchpad.net/~dominik-stadler/+archive/ubuntu/dsta-focal-ppa

**Comment by ALchEmiXt** [comment]
> We unfortunately do not have much influence on Debian/Ubuntu packaging right now, Qt5 support was available on latest master for some time, but the package still got removed, maybe an official release with this was missing (which is available now as 0.5).
> 
> If you would like to install it via deb-packages on Ubuntu or Debian, there are fairly up-to-date PPAs at the following locations:
> 
> * https://launchpad.net/~dominik-stadler/+archive/ubuntu/dsta-bionic-ppa
> * https://launchpad.net/~dominik-stadler/+archive/ubuntu/dsta-eoan-ppa
> * https://launchpad.net/~dominik-stadler/+archive/ubuntu/dsta-focal-ppa

Thanks. Works like a charm. 
Is this now a Qt5 port or a way around to get Qt4 working?

**Comment by centic9** [comment]
Good to hear. 

It's a full port, no dependency on qt4 any more. 

See e.g. the dependencies at https://github.com/openambitproject/openambit/blob/master/src/openambit/CMakeLists.txt and https://github.com/openambitproject/openambit/blob/master/src/movescount/CMakeLists.txt
