### ISSUE TITLE
don't work 

### ISSUE THREAD

**Issue by PankovIlya** [openambitproject/openambit#254]
Nothing happens.

![Screenshot from 2020-07-10 09-35-09](https://user-images.githubusercontent.com/6637853/87124103-c2f2e980-c290-11ea-8d49-dfe909a8052a.png)

test result 
[CMakeError.log](https://github.com/openambitproject/openambit/files/4901423/CMakeError.log)
[CMakeOutput.log](https://github.com/openambitproject/openambit/files/4901424/CMakeOutput.log)

**Comment by centic9** [comment]
Simply Openambit does not find a device, so you might just miss some additional setup, e.g. check the udev-setup as described in the section "Device setup" in the README.

Unfortunately compile-log does not tell much why the device is not found.

If the setup changes do not help, then please run the "openambit-cli" application with the required commandline parameters and post the output.

**Comment by centic9** [comment]
I am closing this as there was no replay for a long time, please provide the requested information if this is still a problem for you.
