### ISSUE TITLE
Fail to connect to movesount (possible HW issue)

### ISSUE THREAD

**Issue by vbelloir** [openambitproject/openambit#255]
Hello all,
my ambit 2 peak is not filling well.
I can't sync it with moveslink2 with a real Windows computer, it fails during sync. moveslink logs are not really verbose.

In ambit 0.15 with Qt 5.12.8 on a Ubuntu 20.04, I got followings logs :
```
Vendor: 1493, Product: 19
libambit_komposti: 2 0 2d 0
Komposit version: 2 0 2d 0
Start reading log...
End reading log...
Start reading navigation...
End reading navigation...
Start sport mode
End reading sport mode
Outer space debug message
Start sync Orbit
Failed to upload log, movescount.com replied with " "" "
End Orbit sync
Failed to upload log, movescount.com replied with " "" "
Failed to upload log, movescount.com replied with " "" "
Failed to upload log (err code: QNetworkReply::InternalServerError ), movescount.com replied with " "\"Object reference not set to an instance of an object.\"" "
Failed to upload log, movescount.com replied with " "" "
Failed to upload log, movescount.com replied with " "" "
```

There are several issues with `Failed to upload log, movescount.com replied with....` but it doesn't really help.
My watch is still present in movescount account.

Any help to save my watch is appreciated.

**Comment by Gerold-R** [comment]
Hi 
Do you see errors in the logbook of the watch? Like error 12 or error 62?
See photo.
![2014-07-29  Error_12_2](https://user-images.githubusercontent.com/16975317/89110993-ff110880-d450-11ea-95df-241080df0e76.JPG)

Gerold

**Comment by vbelloir** [comment]
Thanks for your answer.  
I can't access to the watch interface.
The only screen I can get is a screen saying that I must connect watch to moveslink...

![image](https://user-images.githubusercontent.com/13942805/89128454-f8889c80-d4f5-11ea-85ca-bfabca4e2e21.png)

Really don't know what to do.

**Comment by Gerold-R** [comment]
Hi
Is this new? I tought, that you can sync with Moveslink and you got errors?

Is the watch still detected under Windows? Try a program like USBView or USBDeView (without MovesLink running)
[https://www.nirsoft.net/utils/usb_devices_view.html](url)
![USBDeView](https://user-images.githubusercontent.com/16975317/89150376-b3e51b80-d55e-11ea-9147-35fe99ef9022.png)

If the watch is not detected, check the cable or try another cable. Maybe you know someone else with an Ambit and you can test your watch with the persons cable.

The buttons are still working? Do you hear an audible response when you press a button or the backlight goes on?

If the buttons are working, can you enter the system menu by pressing the "Back/Lap" and "Start/Stop" together for a about 10 seconds? Did you try a reset by pressing all 5 buttons together for a while?

In the case, that you can loose your unsynced workouts, you could try a "Force Firmware Update" using Moveslink.

BTW: did you change anything in your watch or Movescount settings, before you got this error? Switching back to the old settings may help. 
I heard that changing the language may cause this "Connect to Moveslink" message. Personally, I use English even it's not my mother language.

Gerold

PS:
To avoid to bother others with our conversation cause this has nothing to do with OpenAmbit, you can also contact me directly via email Gerold.Ruhland at gmx-topmail.de

**Comment by vbelloir** [comment]
You are right, This is not related directly to OpenAmbit. I posted here to see if logs could help to debug.
I close issue, and continue by email.
