### ISSUE TITLE
trying to connect to Ambit 3

### ISSUE THREAD

**Issue by adzweig** [openambitproject/openambit#261]
Hi 
I try to connect openambit to my Ambit 3. I obtain the message "permission denied"
From glancing through various advice, I wanted to try to run the command

sudo cp ./src/libambit/libambit.rules /etc/udev/rules.d/

However I don't find the file libambit.rules.

Any help to get this connection running is much appreciated.

thanks

Adrian

**Comment by centic9** [comment]
How do you install openambit?

In the sources the file is there, see https://github.com/openambitproject/openambit/blob/master/src/libambit/libambit.rules

**Comment by adzweig** [comment]
thanks a lot. I rebuilt the app. It now seems to work. :-)
