### ISSUE TITLE
Will this work on any BSD system?

### ISSUE THREAD

**Issue by inf3rno** [openambitproject/openambit#264]
The FreeBSD I use has a Linux compatibility layer.  [link](https://www.freebsd.org/doc/handbook/linuxemu.html) Will I be able to use libambit on it? All I need is the GPX files of the last runs, nothing fancy.

**Comment by centic9** [comment]
As long as the required dependencies are available, it should work. 

I have no experience with FreeBSD itself, but if the binary-compatibility-layer is good, you could try to extract the binaries, e.g. from the deb-package from the PPA for Ubuntu at https://launchpad.net/~dominik-stadler/+archive/ubuntu/dsta-focal-ppa/+sourcepub/11435798/+listing-archive-extra

You can also try to compile native binaries, see https://github.com/openambitproject/openambit/blob/master/README.rst#requirements for the list of packages installed on Ubuntu, you will need to install a similar list of tools and libraries if available.

**Comment by inf3rno** [comment]
@centic9 Thanks! I will try.

**Comment by centic9** [comment]
Closing this for now, if you have success and can provide some notes for others, please post them into a new issue so we can add them.

**Comment by inf3rno** [comment]
@centic9 Okay, maybe next month I'll have more time to experiment with this.
