### ISSUE TITLE
Maybe it depends on what you are using to sync your moves. My latest move (~8km walk) appears in MovesCount.

### ISSUE THREAD

**Issue by fmoerl-real** [openambitproject/openambit#270]
Maybe it depends on what you are using to sync your moves. My latest move (~8km walk) appears in MovesCount.

_Originally posted by @Gerold-R in https://github.com/openambitproject/openambit/issues/216#issuecomment-777736744_

it works well using openambit for half a year. Now, there is no connections possible to movescount. Anyway, for me, movescount isn't important. I want my logs and an upload to strava.

**Comment by centic9** [comment]
Thanks for the note. 

See the discussion in #216 for some hints on how to get settings and for now even moves synced. The new APPKEY is added now in Openambit, but you will need an updated userKey to match that which you get via Suuntolink or the hints in #272.

There is a script "stravauploader" now available in the tools-directory, there is some related discussion in #269.
