### ISSUE TITLE
Differences in swim logs

### ISSUE THREAD

**Issue by mbernasocchi** [openambitproject/openambit#28]
From Owen Delaney:
Hi. I've diff'd a .log file generated by openambit and an .xml file generated by the moveslink windows app, and there's a fair amount of differences. For some reason, openambit isn't generating .xml files as well, just the .log files. the .openambit/movescount folder didn't previously exist, so I created it, but only .log files appear there when I sync, no .xml files.
The activity is an indoor swim.
Thanks
Owen

Logs: https://gist.github.com/mbernasocchi/9213828

**Comment by svenstorp** [comment]
@battlegarden Unfortunately there is no upload function for binary files on github. You can email them to me instead, emil at openambit dot org
Thanks!

**Comment by landas** [comment]
Closing issue without any recent activity. Feel free to reopen if issue is still relevant.

**Comment by hdoupe** [comment]
I think I've run into the same issue with lap swimming. Is there anything that I can do to help out? I'm happy to share some swim data saved using the MacOS moveslink app.
