### ISSUE TITLE
Compilation issue on master: this_thread::sleep_for

### ISSUE THREAD

**Issue by jakjas-repo** [openambitproject/openambit#280]
On master (commit: 85dea157ae31d8bbf01941a279eaeefd6901927e) 

I got compilation error: 

> ./src/openambit/src/openambit-cli/Task.cpp: In function ‘void startSync(ambit_object_t*, ambit_personal_settings_t*, MovesCount*, bool, bool, bool, bool, bool, bool, bool, const char*, const char*, bool, Task*)’:
> ./src/openambit/src/openambit-cli/Task.cpp:245:35: error: ‘sleep_for’ is not a member of ‘std::this_thread’
>   245 |                 std::this_thread::sleep_for(std::chrono::milliseconds(5000));
>       |                                   ^~~~~~~~~
> make[2]: *** [CMakeFiles/openambit-cli.dir/build.make:104: CMakeFiles/openambit-cli.dir/Task.cpp.o] Error 1
> make[2]: *** Waiting for unfinished jobs....
> make[1]: *** [CMakeFiles/Makefile2:84: CMakeFiles/openambit-cli.dir/all] Error 2
> make: *** [Makefile:136: all] Error 2
> ==> ERROR: A failure occurred in build().
>     Aborting...
> ==> ERROR: Makepkg was unable to build openambit.

Problem could be solved by adding below code to: ./src/openambit-cli/Task.cpp: 

`#include <thread>`

Diff with changes: https://pastebin.com/p9mkFWZX

**Comment by centic9** [comment]
Can you list which version of gcc/gcc++/stdlib you are using as it worked fine for me on Ubuntu 20.04?

**Comment by jakjas-repo** [comment]
I work on Manjaro: 

local/gcc 11.1.0-1 (base-devel)
local/gcc-libs 11.1.0-1
