### ISSUE TITLE
Convert GPX to JSON route

### ISSUE THREAD

**Issue by pcotret** [openambitproject/openambit#289]
I was looking at this: https://github.com/openambitproject/openambit/wiki/Adjusting-watch-settings-and-routes-without-Movescount#upload-custom-routes

Simple question: is there a script to convert a GPX file to the required JSON format (I'm a bit lazy to do this manually...)

**Comment by battila** [comment]
Hey,

I no longer have any ambit watch, but if you send me some (Ambit/Suunto)
GPX files, I can write a python script to convert the GPX to JSON.

Cheers,
Attila

**Comment by centic9** [comment]
I have published my Java-based tool at https://github.com/centic9/gpx2route now, this can convert GPX files to route. Only note that you may need to "trim down" GPX files first, see https://github.com/centic9/gpx2route/blob/master/src/main/java/org/dstadler/suunto/gpx/ConvertGPXToRoute.java#L20 for some more details

**Comment by pcotret** [comment]
Thanks @centic9 ! I'll have a  look at it.
