### ISSUE TITLE
Qt5 OpenAmbit client

### ISSUE THREAD

**Issue by mariusor** [openambitproject/openambit#37]
Hi, I have created a branch[1] for the OpenAmbit client to compile under Qt5.

I would like to know if there is any interest in this, and if you guys would consider a merge, which way should we do it - parallel builds for Qt4 and Qt5 or moving just to Qt5.

Thank you.

[1] https://github.com/habarnam/openambit/tree/Qt5_Client

**Comment by manisandro** [comment]
Qt5 support added in 566939bf3b34788161f314cb6367c71b8162b926
