### ISSUE TITLE
Openambit stopped working with Suunto Firmware 2.0.9

### ISSUE THREAD

**Issue by pgastinger** [openambitproject/openambit#42]
Hi, 

I have been using Openambit for the last couple of weeks and it basically worked. I updated my Suunto Ambit 2S-Firmware to 2.0.9 yesterday and since then, my watch says "Please update Moveslink". 
I tried to delete my .openambit-directory but it didn't help. My guess is that Suunto changed something or implemented further checking.
Is there any fix for that? Thank you!

best regards, 
Peter

**Comment by henriferr** [comment]
Would communications protocol of the first openambit release also work with the Suunto Quest watch? 
I am looking for support for Suunto Quest watch?
