### ISSUE TITLE
Open water swimming log don't sync

### ISSUE THREAD

**Issue by josesj** [openambitproject/openambit#55]
Using an Ambit 2S the open water swimming logs don't sync with Movescount.

**Comment by svenstorp** [comment]
@strawpants Please email them to emil at openambit dot org
Thanks!

**Comment by strawpants** [comment]
They are on their way

**Comment by strawpants** [comment]
My swim logs sync fine to movescount now, but this holds for an indoor swimming log, don't know about openwater swimming.

**Comment by landas** [comment]
Closing issue without any recent activity. Feel free to reopen if issue is still relevant.
