### ISSUE TITLE
Separation of Packet Logic from HID Device access

### ISSUE THREAD

**Issue by uvwxy** [openambitproject/openambit#58]
Would it be possible to separate the packet logic from the transfer?

I started the [android-ambit](https://github.com/uvwxy/android-ambit) repo a while ago. Access to HID device is done. Now I would like to use the existing code base to read/write to the device.

As the de/serializing of packets into the structs is mixed with writing them to a device (the same memory is used), I could not directly use the code via Java JNDI bindings.
(See `libambit_protocol_command(...)` in [protocol.c](https://github.com/openambitproject/openambit/blob/master/src/libambit/protocol.c))

If someone could separate the logic, I can wrap around openambit to create the messages and handle the transfer of the messages to/from the device according to the available HID interface on Android.

What do you think?

**Comment by centic9** [comment]
The project at android-ambit was not updated for quite some time and there is now https://github.com/starryalley/AmbitSync which is based on Openambit/libambit, so I think there is not a lot of reason to work on this some more for now.
