### ISSUE TITLE
Implement i18n in OpenAmbit

### ISSUE THREAD

**Issue by bubulle** [openambitproject/openambit#63]
An interesting feature would be implementing internationalization so that the program dialogs, menus, messages, etc. can be localized to various languages.

Being a C++ app, I suspect this is mostly about using gettext features for this but even though I'm involved in FLOSS localization for years, I don't have much clues about The Right Way to do it, not being skilled in programming, myself.

**Comment by paddy-hack** [comment]
So we agreed on UTF-8 for `libambit` and all strings coming in are properly converted.  We have translations for the GUI in several languages and I even added the (horrible?) Dutch (in 4e6f6a6) and Japanese (in 2f0c84a) message catalogs that I mentioned earlier.  I'd say this can be closed.
