### ISSUE TITLE
Investigate character encoding in Ambit devices

### ISSUE THREAD

**Issue by svenstorp** [openambitproject/openambit#70]
The character encoding of the freetext strings in the devices needs to be investigated, today ISO-8859-1 is assumed, but is not necessarily correct. Evaluation is required for both Ambit/Ambit2 and Ambit3. Issue related to #63.

**HELPING OUT:**
  - Start PCAP dump (howto: http://openambit.org/wireshark-dissector)
  - Create new Sport mode with lots of nasty special characters on movescount.com
  - Sync device with Moveslink
  - Record an exercise (10 seconds duration is sufficient)
  - Sync new exercise with Moveslink
  - Stop PCAP dump
  - Repeat the above for all available languages (device setting on movescount.com)
  - Send PCAP-dumps to emil at openambit.org

**Comment by paddy-hack** [comment]
> When other encodings are encountered in the wild I'll be more than happy to address that.

As part of another issue :wink:
