### ISSUE TITLE
Add functionality for resyncing moves deleted on movescount.com

### ISSUE THREAD

**Issue by gelim** [openambitproject/openambit#75]
Hi,

I've synced some runs from to movescount, then I deleted by hand some runs in the web interface.
If I try to manually resync those moves from the app ("write to movescount file") I got the following console error :

```
Failed to upload log, movescount.com replied with " ""Move already exists (UserDeviceID: XXXXXX, StartTime_LT: 11\/2\/2014 5:24:22 PM, move.Duration.TotalSeconds: 3109.4)"" "
```

If I list the moves from their REST API I got 0 moves.

```
curl -XGET http://uiservices.movescount.com/moves/private?appkey={APPKEY}&userkey={USERKEY}&email={EMAIL}
[]
```

I'm not sure if the problem is from their REST API, or the app not doing the proper things.
Cheers,

**Comment by landas** [comment]
Closing issue without any recent activity. Feel free to reopen if issue is still relevant.
