### ISSUE TITLE
Should the log store format change?

### ISSUE THREAD

**Issue by svenstorp** [openambitproject/openambit#76]
Today all synced moves are stored as XML-files in ~/.openambit. Those XML-files are pretty space consuming, typically > 2 MB / hour of exercise. XML was chosen since it is easy to read, and compare to Moveslink.
Possible options:
- Compressing the XML
- Leightweight database (for example SQLite)
- ???

**Comment by landas** [comment]
Closing issue without any recent activity. Feel free to reopen if issue is still relevant.
