### ISSUE TITLE
Add cmake qt 4.x (+dev) and zlib to list of dependencies. Update build instructions

### ISSUE THREAD

**Issue by mmihalko** [openambitproject/openambit#79]
Some dependencies are missing in the readme. Also build instructions seems to me bit outdated, when you provide nice build script.

**Comment by paddy-hack** [comment]
A bit late (me and the project admins were hibernating :wink:) but I pushed a new README.  If there's anything you think needs fixing, clarification on adding, feel free to reopen this issue or open a new one.
