### ISSUE TITLE
Should we drop debian packaging support?

### ISSUE THREAD

**Issue by paddy-hack** [openambitproject/openambit#82]
Seeing that @bubulle has picked up the Debian packaging (with these packages downstreaming to Ubuntu as well), I wonder if we should keep maintaining our own.  If not, we can drop the `src/libambit/debian/` and `src/openambit/debian/` directories.

I went through the content of both directories and both looked like rather plain vanilla packaging.  If user needs are not met by their distribution's Openambit packages, they'd be better off by compiling from source (and install *outside* the distribution's locations, see #78) anyway.
FWIW, we don't have any RPM packaging support either.

What do you think?  It's just a simple `git rm -r` and one thing less to worry about ;-)
On the other hand, we have to find and/or keep distribution maintainers happy.

**Comment by svenstorp** [comment]
Totally agree!
