### ISSUE TITLE
Remove Qt dependencies from libmovescount

### ISSUE THREAD

**Issue by paddy-hack** [openambitproject/openambit#84]
Once #83 is done, it would be nice to remove the dependency on Qt for `libmovescount`.  I have no idea what kind of work will be needed for this but I'd like to see `libmovescount` implemented in such a way that it only relies on C/C++, a _common_ JSON library, a _common_ XML library and a _common_ networking library.  Where _common_ implies it does not depend on any specific GUI toolkit.  If any of these aren't really needed, so much the better.

Going through the `#include` statements, I noticed thread and regex related Qt includes.  As of C++11, these are part of the C++ language.  Doing the libary in C would mean use of `pthreads` and `regex` API.  Possible of course, but not exactly pretty.

**Comment by svenstorp** [comment]
Personally I'm not sure it is worth the pain.
Qt is not *that* uncommon and it is not only a GUI toolkit! Qt is separated into several libs where only a few of them are GUI-related. For libmovescount we would only be dependent on QtCore and QtNetwork, in Qt5 Json support is even built in.

**Comment by landas** [comment]
Closing issue without any recent activity. Feel free to reopen if issue is still relevant.
