### ISSUE TITLE
Spec for .log files

### ISSUE THREAD

**Issue by PowerTap** [openambitproject/openambit#92]
Is there a written spec for the .log files stored in ~/.openambit?  I'm looking to do some processing with them locally.

**Comment by paddy-hack** [comment]
I don't think there is one.  From what I understand, the `.log` files in `~/.openambit` were written to follow the XML files from Moveslink2 as closely as possible.  There is even a `movescountXmldiff.pl` utility to compare them.
Just out of curiosity, what kind of processing are you thinking of?

**Comment by PowerTap** [comment]
I was looking to chart my data in ways that MovesCount doesn't seem to support.
