### ISSUE TITLE
Failed to convert log to gpx, AttributeError: 'int' object has no attribute 'split' in utcSplitConvSeconds function

### ISSUE THREAD

**Issue by mbanas** [openambitproject/openambit#93]
Hi,
I'm having issues converting some of my log files to gpx. Could you please check why it's not working? I was trying to debug the issue, but I really don't know what happens with lapArray[] here..

Here're two log files:
bad.log - logfile showing the error
good.log - logfile with no error

https://www.dropbox.com/sh/3petzerbc87nl49/AAAurJOvsuUXHVuuyS99xnhHa?dl=0

Thanks for support! Let me know if I can help you somehow.

**Comment by paddy-hack** [comment]
I ran both logs through `python tools/openambit2gpx.py`.  The `good.log` completed without any problem.  The `bad.log` produces
```
Traceback (most recent call last):
  File "openambit2gpx.py", line 207, in <module>
    latInterPolEP=str( ((lat2-lat1)/timeDiff(t1,t2))*timeDiff(t1,t) + lat1 )
  File "openambit2gpx.py", line 66, in timeDiff
    secs2=utcSplitConvSeconds(utcTime2)
  File "openambit2gpx.py", line 55, in utcSplitConvSeconds
    tmpTime=utcTime.split("T")[1].split("Z")[0].split(":")
AttributeError: 'int' object has no attribute 'split'
```
Looking at the content of the `lapArray[i]` that triggers this
```
['Manual', '2015-01-13T17:32:07', '2670000', '6671', '2015-01-13T17:16:35.792Z', '49.223108', '16.5919296', '2015-01-13T17:16:32.188Z', 0, 0, 0]
```
shows that `t2`, the last element of `lapArray[i]`, is indeed an `int`, hence the `AttributeError`.  Why this is is an `int` is another issue for which I have no answer.

FWIW, the `good.log` never takes that branch of the code.

**Comment by marguslt** [comment]
Something  with handling manual laps,  none of those in `good.log` 
Before exception is thrown, your GPX is actually finished. So If you just want to use you track and do not care about gpx lap extensions, you can manually open output file and change last line from
`<extensions>` to `</gpx>` . Or remove lap extension code for now.

**Comment by landas** [comment]
Closing issue without any recent activity. Feel free to reopen if issue is still relevant.
