### ISSUE TITLE
Failed to upload log, movescount.com replied with " ""For given appkey+userkey no safe userkey were found"" "

### ISSUE THREAD

**Issue by aicastell** [openambitproject/openambit#96]
When I try to "Write movescount file" on a route (right button), I get this message on the terminal:

Failed to upload log, movescount.com replied with " ""For given appkey+userkey no safe userkey were found"" "

And the route is not uploaded to my movescount account.

Is this functionality implemented?

**Comment by marguslt** [comment]
Apparently settings are not checked when triggering Movescount write. 
In Openambit, select *File -> Settings -> Movescount*, enable *Sync logs with Movescount* and enter e-mail used for Movescount. Next time you open movescount.com you should see pop-up that is requesting premissions for Moveslink, if not, head directly to http://www.movescount.com/settings#connections andAllow Moveslink from there.

But something is indeed changed, Movescount does gives me *NO CONNECTIONS YET* under Connections, while there should be several Moveslink records.

**Comment by aicastell** [comment]
> In Openambit, select File -> Settings -> Movescount, 
> enable Sync logs with Movescount 
> and enter e-mail used for Movescount.

Done!

> head directly to http://www.movescount.com/settings#connections 
> and allow Moveslink from there.

Done! 

Now when I try to upload a route, openambits shows this message on the console, in an infinite loop:

Failed to upload log, movescount.com replied with " ""Device creation not allowed. Suunto devices must be created by POSTing a new UserDevice."" " 

I don't have any device added on my Movescount account. I can't add it, because movescount web page doesn't allow me to create a new Suntoo device, because It requests the download of a windows application, and I am linux user (don't use windows).

**Comment by marguslt** [comment]
It's a known issue, check  #73 
Not sure what's the status with natanojl/openambit@653b7af72a215b6d517e763dc919e28392f05783

Depending on your views to anything-windows, available HW and bandwidth, one possibility might be installing a VirtualBox, get Windows image from https://www.modern.ie/en-us/virtualization-tools#downloads and do a one time install of Moveslink just to add your watch to Movescount.
Technically it works, I'm updating my Ambit sports modes from time to time.

**Comment by paddy-hack** [comment]
I've been looking into #73 and natanojl/openambit@653b7af does seem to work with a few caveats.  Please see #73 for my comments.
