### ISSUE TITLE
Openambit behind a proxy

### ISSUE THREAD

**Issue by gauthierelcapitan** [openambitproject/openambit#97]
Is it possible to use openambit behind a proxy ?

**Comment by paddy-hack** [comment]
I couldn't quite find out what the default Qt proxy behaviour is from the documentation but based on that documentation and the `openambit` code, I think `openambit` does not support proxied access.  Why don't you give it a try by starting `openambit` from the command-line with an appropriate value for `http_proxy` and/or `https_proxy`?  Something like
```
http_proxy=http://proxy.example.com:8080/ openambit
```
might just work.

**Comment by landas** [comment]
Closing issue without any recent activity. Feel free to re-add issue as feature request if still relevant.
