### ISSUE TITLE
Building with make-option -j to build in parallel fails

### ISSUE THREAD

**Issue by centic9** [openambitproject/openambit#99]
When I try to package the latest openambit and build it for Ubuntu, it fails with 

```
make[4]: *** No rule to make target `src/openambit/../libambit/libambit.so.0', needed by `src/openambit/openambit'.  Stop.
````

When I remove the "-j" option in the call to make, compiling works, so it seems something in the generated Makefiles does not support parallel building correctly now.

See also https://launchpad.net/~dominik-stadler/+archive/ubuntu/ppa/+build/7550585/+files/buildlog_ubuntu-trusty-i386.openambit_0.3-1ubuntu0%7Egit20150614%7Eppa2_BUILDING.txt.gz for the full build-output.

**Comment by paddy-hack** [comment]
Seeing that a serial build works just fine for you I suggest that you use that for now.

The most likely reason that the parallel build does not work is that the `add_subdirectory` entries in the top-level `CMakeLists.txt` do not impose a build order.  At this point I know too little about `cmake` to fix this quickly.  A quick glance at `add_dependency` suggests that that might fix things.

**Comment by centic9** [comment]
Yes, I am fine with non-parallel build for now, however as parallel-building is the default in the current Ubuntu/Debian package it might make sense to fix it before doing the next release-package.

**Comment by paddy-hack** [comment]
I just confirmed that running a second parallel `make` will fix things as well.
